### ISSUE TITLE
naming is non-standard

### ISSUE THREAD

**Issue by tacman** [openai-php/symfony#18]
The naming for this bundle isn't standard, and probably doesn't comply with Symfony's trademark permissions.

A better name would be something like 

    openai/openai-bundle

Using symfony as the bundle name is confusing, I think most people looking for a bundle to wrap the openai php client would intuitively search for openai-bundle, I know I would.

**Comment by nunomaduro** [comment]
No plans for that.

**Comment by GromNaN** [comment]
In packagist you can search for type:symfony-bundle. There is no convention for the package name.
