### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by pkothmair** [openai-php/symfony#5]
Hey could you update the openai-php/client dependency?
You are still using v0.4.1 when there’s already v0.6.1 out
Thank you

**Comment by nunomaduro** [comment]
cc @GromNaN @gehrisandro

**Comment by GromNaN** [comment]
I opened a PR to allow the new versions to be installed #6

**Comment by chekalsky** [comment]
@nunomaduro could you also create a new tag for a package, please?
