### ISSUE TITLE
Would it be possible to have a version that calls the latest openai-php/client version? 

### ISSUE THREAD

**Issue by CedCannes** [openai-php/symfony#7]
The version of openai-php/client in composer.json is not up to date. This will happen with each new update.
Isn't there a way to have a (e.g. "latest" or something) version that always uses the latest version of the client, at our own risk? 

https://github.com/openai-php/symfony/blob/de75b44e4b517374c20e4c31c7a1aecc6c964f3b/composer.json#L16

**Comment by GromNaN** [comment]
Yes, can you please open a PR?

**Comment by Sam152** [comment]
I was able to work around this by requiring the client directly and aliasing it:

```
composer require "openai-php/client:v0.7.3 as v0.4.1"
```

This will become less of an issue after 1.0 is tagged, since a new version of this bundle will only need to be tagged for every new major version of the client.

**Comment by CedCannes** [comment]
> I was able to work around this by requiring the client directly and aliasing it:
> 
> ```
> composer require "openai-php/client:v0.7.3 as v0.4.1"
> ```
> 
> This will become less of an issue after 1.0 is tagged, since a new version of this bundle will only need to be tagged for every new major version of the client.

Great, I didn't know this tip, thank you. :+1:
